importScript("TestQPoint.js");
importScript("TestQSize.js");
importScript("TestQRect.js");
importScript("TestQColor.js");
importScript("TestQFont.js")
importScript("TestQByteArray.js");
importScript("TestQDir.js");
importScript("TestQIODevice.js");
importScript("TestQFileInfo.js");
importScript("TestQFileDevice.js");
importScript("TestQFile.js");
importScript("TestQSaveFile.js");
importScript("TestQTemporaryFile.js");
importScript("TestQUrl.js");
importScript("TestQNetworkRequest.js")
importScript("TestQNetworkReply.js")
importScript("TestQNetworkAccessManager.js")

testQPoint();
testQSize();
testQRect();
testQColor();
testQFont();
testQByteArray();
testQDir();
testQIODevice();
testQFileInfo();
testQFileDevice();
testQFile();
testQSaveFile();
testQTemporaryFile();
testQUrl();
testQNetworkRequest();
testQNetworkReply();
testQNetworkAccessManager();
